Repository study-basic-hackathon/album, pull requests merged in 2025-06, with the labels that each got.

#86 華展作品一覧ページ (static) の作成
  client/src/main.tsx
  client/src/pages/Exhibition.tsx
  client/src/pages/Index.tsx
  client/src/pages/exhibition.css
Labels: フロントエンド

#99 WorkItemsのレスポンスを単一に修正
  api/src/app.js
Labels: バックエンド

#112 トップページと華展作品一覧とのルーティングの実装
  client/src/App.tsx
  client/src/main.tsx
  client/src/pages/Exhibition.tsx
  client/src/pages/Index.tsx
Labels: フロントエンド

#118 華展作品一覧ページ <-> 作品ページのルーティングの実装
  client/src/App.tsx
  client/src/components/WorkImages.tsx
  client/src/components/WorkMetadata.tsx
  client/src/pages/Exhibition.tsx
  client/src/pages/ExhibitionWork.tsx
  client/src/pages/Index.tsx
Labels: フロントエンド

#115 重複排除のためにARRAY_ARG関数にDISTINCTを追加
  api/src/app.js
Labels: バックエンド

#135 exhibition, arranger, materialの各エンドポイントの修正
  api/src/app.js
Labels: bug

#132 季節の作品の一覧のリファクタリング
  api/src/app.js
Labels: バックエンド

#147 カテゴリの作品の取得のGROUP BYに登録日時を追加
  api/src/app.js
Labels: バックエンド

#150 季節の作品の取得のORDER BYを登録日時に修正
  api/src/app.js
Labels: バックエンド

#148 カテゴリの作品の取得のORDER BYを登録日時に修正
  api/src/app.js
Labels: バックエンド

#160 華展作品一覧ページで API を使用
  client/src/api/exhibition.ts
  client/src/pages/Exhibition.tsx
Labels: フロントエンド

#164 モックサーバーとの通信設計: 華展作品ページで API を使用
  client/src/App.tsx
  client/src/api/arranger.ts
  client/src/api/category.ts
  client/src/api/exhibition.ts
  client/src/api/material.ts
  client/src/api/season.ts
  client/src/components/WorkImages.tsx
  client/src/hooks/arranger.ts
  client/src/hooks/category.ts
  client/src/hooks/exhibition.ts
  client/src/hooks/material.ts
  client/src/hooks/season.ts
  client/src/pages/Exhibition.tsx
  client/src/pages/ExhibitionWork.tsx
  client/src/pages/Index.tsx
Labels: フロントエンド

#166 全ページで API を使用
  client/src/App.tsx
  client/src/api/arranger.ts
  client/src/api/category.ts
  client/src/api/exhibition.ts
  client/src/api/material.ts
  client/src/api/season.ts
  client/src/components/WorkImages.tsx
  client/src/components/WorkMetadata.tsx
  client/src/hooks/arranger.ts
  client/src/hooks/category.ts
  client/src/hooks/exhibition.ts
  client/src/hooks/material.ts
  client/src/hooks/season.ts
  client/src/mocks/handlers/arranger.ts
  client/src/mocks/handlers/category.ts
  client/src/mocks/handlers/exhibition.ts
  client/src/mocks/handlers/image.ts
  client/src/mocks/handlers/index.ts
  client/src/mocks/handlers/material.ts
  client/src/mocks/handlers/season.ts
  client/src/mocks/handlers/work.ts
  client/src/pages/Arranger.tsx
  client/src/pages/ArrangerWork.tsx
  client/src/pages/Category.tsx
  client/src/pages/CategoryWork.tsx
  client/src/pages/ExhibitionWork.tsx
  client/src/pages/Material.tsx
  client/src/pages/MaterialWork.tsx
  client/src/pages/Season.tsx
  client/src/pages/SeasonWork.tsx
  client/src/types/api.ts
  client/vite.config.ts
Labels: フロントエンド

#165 関心ごとに基づくファイルの整理
  api/src/app.js
  api/src/repositories/arranger.js
  api/src/repositories/category.js
  api/src/repositories/exhibition.js
  api/src/repositories/formattedWorkList.js
  api/src/repositories/image.js
  api/src/repositories/material.js
  api/src/repositories/season.js
  api/src/routers/arranger.js
  api/src/routers/category.js
  api/src/routers/exhibition.js
  api/src/routers/image.js
  api/src/routers/material.js
  api/src/routers/season.js
  api/src/usecases/arranger.js
  api/src/usecases/category.js
  api/src/usecases/exhibition.js
  api/src/usecases/image.js
  api/src/usecases/material.js
  api/src/usecases/season.js
Labels: バックエンド

#167 コードフォーマッターによるインデントの統一及びapp.jsで使用されないimport文を削除
  api/sql/1_data.sql
  api/src/app.js
  api/src/repositories/arranger.js
  api/src/repositories/category.js
  api/src/repositories/exhibition.js
  api/src/repositories/image.js
  api/src/routers/arranger.js
  api/upload/1.png
Labels: バックエンド

#169 作品の一覧の取得および作品の取得で返される値に、exhibition_idを追加した
  api/src/repositories/formattedWorkList.js
Labels: バックエンド

#174 作者の更新
  api/src/repositories/putArranger.js
  api/src/routers/putArranger.js
  api/src/usecases/putArranger.js
Labels: バックエンド

#179 作者の更新の追加/修正
  api/src/repositories/arranger.js
  api/src/repositories/putArranger.js
  api/src/routers/arranger.js
  api/src/routers/putArranger.js
  api/src/usecases/arranger.js
  api/src/usecases/putArranger.js
Labels: バックエンド

#178 季節の更新の追加
  api/src/repositories/season.js
  api/src/routers/season.js
  api/src/usecases/season.js
Labels: バックエンド

#175 華展の更新
  api/src/repositories/exhibition.js
  api/src/routers/exhibition.js
  api/src/usecases/exhibition.js
Labels: バックエンド

#176 花材の更新
  api/src/repositories/material.js
  api/src/routers/material.js
  api/src/routers/putMaterial.js
  api/src/usecases/material.js
Labels: バックエンド

#177 カテゴリの更新の追加
  api/src/repositories/category.js
  api/src/routers/category.js
  api/src/usecases/category.js
Labels: バックエンド

#181 更新の修正
  api/src/app.js
  api/src/repositories/exhibition.js
  api/src/routers/arranger.js
  api/src/routers/category.js
  api/src/routers/exhibition.js
  api/src/routers/material.js
  api/src/routers/putMaterial.js
  api/src/routers/season.js
  api/src/usecases/arranger.js
  api/src/usecases/category.js
  api/src/usecases/exhibition.js
  api/src/usecases/material.js
  api/src/usecases/season.js
Labels: バックエンド

#182 更新の修正
  api/src/usecases/arranger.js
  api/src/usecases/category.js
  api/src/usecases/exhibition.js
  api/src/usecases/material.js
  api/src/usecases/season.js
Labels: バックエンド

#192 `client` のリファクタリング
  client/src/components/WorkImages.tsx
  client/src/components/WorksImages.tsx
  client/src/pages/Arranger.tsx
  client/src/pages/ArrangerWork.tsx
  client/src/pages/Category.tsx
  client/src/pages/CategoryWork.tsx
  client/src/pages/Exhibition.tsx
  client/src/pages/ExhibitionWork.tsx
  client/src/pages/Index.tsx
  client/src/pages/Material.tsx
  client/src/pages/MaterialWork.tsx
  client/src/pages/Season.tsx
  client/src/pages/SeasonWork.tsx
Labels: フロントエンド

#196 トップページのフェッチ処理時状態遷移のリファクタリング
  client/src/pages/Index.tsx
Labels: bug, フロントエンド

#200 SCSS 環境の設定
  client/package-lock.json
  client/package.json
  client/src/App.scss
  client/src/main.tsx
  client/src/scss-global/_reset.scss
  client/src/scss-global/_typography.scss
  client/src/scss-global/_variable.scss
  client/src/scss-global/index.scss
Labels: フロントエンド

#201 レイアウトの基礎を作成
  client/package-lock.json
  client/package.json
  client/src/App.scss
  client/src/App.tsx
  client/src/main.tsx
  client/src/scss-global/_typography.scss
  client/src/scss-global/_variable.scss
  client/src/scss/foundation/_gutter.scss
  client/src/scss/foundation/_reset.scss
  client/src/scss/foundation/_typography.scss
  client/src/scss/foundation/_variables.scss
  client/src/scss/foundation/index.scss
  client/src/scss/layout/_wrapper.scss
  client/src/scss/layout/index.scss
Labels: フロントエンド
