Repository study-basic-hackathon/album, pull requests merged in 2025-07, with the labels that each got.

#202 トップページのレイアウトを作成
  client/src/App.tsx
  client/src/components/Heading.tsx
  client/src/components/scss/heading.module.scss
  client/src/pages/Index.tsx
  client/src/pages/scss/index.module.scss
  client/src/scss/foundation/_gutter.scss
  client/src/scss/foundation/_typography.scss
  client/src/scss/foundation/_variables.scss
  client/src/scss/foundation/index.scss
  client/src/scss/layout/_body.scss
  client/src/scss/layout/_wrapper.scss
  client/src/scss/layout/index.module.scss
  client/vite.config.ts
Labels: フロントエンド

#203 作品写真が登録されていない場合のフォールバック処理
  client/src/components/WorksImages.tsx
Labels: フロントエンド

#205 グローバルスタイルのリファクタリング
  client/src/components/scss/heading.module.scss
  client/src/components/scss/works-images.module.scss
  client/src/pages/scss/index.module.scss
  client/src/scss/foundation/_typography.scss
  client/src/scss/foundation/_variables.scss
  client/src/scss/layout/_body.scss
  client/src/scss/layout/_wrapper.scss
Labels: フロントエンド

#210 ヘッダーとフッターのデザイン
  client/package-lock.json
  client/package.json
  client/src/App.tsx
  client/src/components/Footer.tsx
  client/src/components/Header.tsx
  client/src/components/HeaderNavigation.tsx
  client/src/components/scss/footer.module.scss
  client/src/components/scss/header.module.scss
  client/src/scss/layout/_wrapper.scss
Labels: フロントエンド

#211 デザインとコンポーネントのリファクタリング
  client/src/components/AdjacentNavigationArrows.tsx
  client/src/components/Fallback.tsx
  client/src/components/HeadingSub.tsx
  client/src/components/WorkImages.tsx
  client/src/components/WorkMetadata.tsx
  client/src/components/scss/adjacent-navigation-arrows.module.scss
  client/src/components/scss/fallback.module.scss
  client/src/components/scss/footer.module.scss
  client/src/components/scss/heading-sub.module.scss
  client/src/components/scss/work-images.module.scss
  client/src/components/scss/work-metadata.module.scss
  client/src/components/scss/works-images.module.scss
  client/src/pages/ArrangerWork.tsx
  client/src/pages/CategoryWork.tsx
  client/src/pages/ExhibitionWork.tsx
  client/src/pages/Index.tsx
  client/src/pages/MaterialWork.tsx
  client/src/pages/SeasonWork.tsx
  client/src/pages/scss/index.module.scss
  client/src/pages/scss/work.module.scss
Labels: フロントエンド

#218 グローバルスタイルの微調整
  client/src/components/Footer.tsx
  client/src/components/scss/footer.module.scss
  client/src/scss/foundation/_reset.scss
  client/src/scss/layout/_wrapper.scss
Labels: フロントエンド

#219 work_imageという中間テーブルの作成とimageテーブルからwork_idを削除
  api/sql/0_init.sql
  api/sql/1_data.sql
Labels: bug

#220 CreateMaterialPathからPathの除外、routers/work.jsでrepositoriesをusecasesに変更
  api/src/routers/work.js
  api/src/usecases/material.js
Labels: バックエンド

#224 work_imageテーブルの作成に伴い、作品一覧取得の関数およびworkのpost処理におけるクエリの修正
  api/src/repositories/formattedWorkList.js
  api/src/repositories/work.js
Labels: bug

#225 `useExhibitions` をリトライできるようにする
  client/src/api/exhibition.ts
  client/src/components/Fallback.tsx
  client/src/hooks/exhibition.ts
  client/src/pages/Index.tsx
  client/src/pages/scss/index.module.scss
Labels: フロントエンド

#227 API が返すエラーメッセージを日本語に翻訳
  client/src/api/arranger.ts
  client/src/api/category.ts
  client/src/api/exhibition.ts
  client/src/api/material.ts
  client/src/api/season.ts
Labels: フロントエンド

#229 ページごとのメタデータの設定
  client/index.html
  client/src/components/Head.tsx
  client/src/components/scss/footer.module.scss
  client/src/pages/Arranger.tsx
  client/src/pages/ArrangerWork.tsx
  client/src/pages/Category.tsx
  client/src/pages/CategoryWork.tsx
  client/src/pages/Exhibition.tsx
  client/src/pages/ExhibitionWork.tsx
  client/src/pages/Index.tsx
  client/src/pages/Material.tsx
  client/src/pages/MaterialWork.tsx
  client/src/pages/Season.tsx
  client/src/pages/SeasonWork.tsx
  client/src/scss/layout/_wrapper.scss
Labels: フロントエンド

#237 imageAPIのdelete処理において、ルータ層のエラーハンドリングの可読性を向上させた
  api/src/repositories/image.js
  api/src/routers/image.js
  api/src/usecases/image.js
  api/src/utils/commons/AppError.js
  api/src/utils/commons/Result.js
Labels: バックエンド

#236 imageAPIのdelete処理において、レポジトリの削除処理を改善した
  api/src/repositories/image.js
  api/src/routers/image.js
  api/src/usecases/image.js
  api/src/utils/commons/Result.js
  api/src/utils/routers/errorHandling.js
Labels: バックエンド
